In [2]:
def simulate(mat, initState, totalTransitions):
    count1 = 0
    currState = initState
    for loopA in range(totalTransitions):
        currState = np.random.choice(np.arange(len(mat)),p=mat[currState,:])
        if(currState == 1):
            count1 += 1
    return count1/totalTransitions

In [3]:
import numpy as np

repetitions = 1000
totalTransitions = 1000

mat = np.array([[0.1, 0.4, 0.5],
                [0.2, 0.2, 0.6],
                [0.1, 0.5, 0.4]])

res = np.zeros(repetitions)
for loopA in range(repetitions):
    res[loopA] = simulate(mat, 0, totalTransitions)
    
print(f"Average fraction of time spent on 1: {np.mean(res)}")

Average fraction of time spent on 1: 0.37394999999999995


In [5]:
mat = np.array([[0,.5,.5,0,0],
               [.5,0,.5,0,0],
               [.333,.333,0,.333,0],
               [0,0,.5,0,.5],
               [.5,0,0,.5,0]])
mat2 = mat
for loopA in range(4):
    print('Iteration: P', loopA)
    mat2 = mat2.dot(mat2)
    print(mat2)

Iteration:  0
[[0.4165 0.1665 0.25   0.1665 0.    ]
 [0.1665 0.4165 0.25   0.1665 0.    ]
 [0.1665 0.1665 0.4995 0.     0.1665]
 [0.4165 0.1665 0.     0.4165 0.    ]
 [0.     0.25   0.5    0.     0.25  ]]
Iteration:  1
[[0.31216675 0.20804175 0.270625   0.16641675 0.041625  ]
 [0.24966675 0.27054175 0.270625   0.16641675 0.041625  ]
 [0.18023625 0.22186125 0.41600025 0.0554445  0.12479175]
 [0.37466675 0.20804175 0.14575    0.27054175 0.        ]
 [0.124875   0.249875   0.43725    0.041625   0.14575   ]]
Iteration:  2
[[0.26571437 0.22629158 0.29581727 0.1483314  0.06149229]
 [0.26180812 0.23019783 0.29581727 0.1483314  0.06149229]
 [0.22299005 0.23253084 0.34452007 0.11017519 0.08683911]
 [0.29653204 0.22285056 0.25775898 0.17824633 0.04244364]
 [0.21397164 0.23566868 0.35310886 0.10393593 0.09140722]]
Iteration:  3
[[0.25295602 0.22855493 0.30740606 0.13840244 0.06785964]
 [0.25294076 0.22857019 0.30740606 0.13840244 0.06785964]
 [0.24820625 0.22911827 0.31250733 0.13418964 0.0705427

In [ ]:
#the m.c. forgets where it starts from with large n